C:\Users\ESSD\AppData\Local\Programs\Python\Python38\python.exe: can't open file 'C:\Users\Administrator\Desktop\code\bitlockerTest\t_Tcg_BitLocker_21_BaseRebootIoTest.py': [Errno 2] No such file or directory
2025-01-07 14:39:17,635 [INFO] 程序已以管理员权限运行。
2025-01-07 14:39:17,636 [INFO] [INFO] Detected post-reboot. Reboot finish...
2025-01-07 14:39:17,655 [INFO] [INFO] Task deleted.
2025-01-07 14:39:17,656 [INFO] [INFO] Workflow completed successfully.
2025-01-07 14:39:17,656 [INFO] 流程完成。
2025-01-07 15:06:54,003 [INFO] 程序已以管理员权限运行。
2025-01-07 15:06:54,004 [INFO] 程序已以管理员权限运行。
2025-01-07 15:06:54,004 [INFO] [INFO] Detected post-reboot. Running disable BitLocker logic...
BitLocker 驱动器加密: 配置工具版本 10.0.19041
版权所有 (C) 2013 Microsoft Corporation。保留所有权利。

请输入密码以解锁此卷: 
错误: 此密码无法解锁卷 D:。
2025-01-07 15:09:07,862 [INFO] FIO read write
2025-01-07 15:09:07,865 [ERROR] 发生异常 : [WinError -2144272384] BitLocker 驱动器加密已锁定该驱动器。必须从控制面板解除此驱动器锁定。: 'D:\\'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\code\bitlockerTest\test_case\t_Tcg_BitLocker_21_BaseRebootIoTest.py", line 175, in Run
    os.makedirs(test_dir)
  File "C:\Users\ESSD\AppData\Local\Programs\Python\Python38\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\ESSD\AppData\Local\Programs\Python\Python38\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [WinError -2144272384] BitLocker 驱动器加密已锁定该驱动器。必须从控制面板解除此驱动器锁定。: 'D:\\'
2025-01-07 15:09:07,871 [INFO] 流程完成。
[DEBUG] Failed to add password protector.
[DEBUG] Return code: 2150694951
2025-01-07 15:16:10,763 [INFO] 程序已以管理员权限运行。
2025-01-07 15:16:10,763 [INFO] 程序已以管理员权限运行。
2025-01-07 15:16:10,764 [INFO] [INFO] Detected post-reboot. Running disable BitLocker logic...
BitLocker 驱动器加密: 配置工具版本 10.0.19041
版权所有 (C) 2013 Microsoft Corporation。保留所有权利。

请输入密码以解锁此卷: 
错误: 此密码无法解锁卷 D:。
2025-01-07 15:16:50,194 [INFO] FIO read write
2025-01-07 15:16:50,194 [ERROR] 发生异常 : [WinError -2144272384] BitLocker 驱动器加密已锁定该驱动器。必须从控制面板解除此驱动器锁定。: 'D:\\'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\code\bitlockerTest\test_case\t_Tcg_BitLocker_21_BaseRebootIoTest.py", line 175, in Run
    os.makedirs(test_dir)
  File "C:\Users\ESSD\AppData\Local\Programs\Python\Python38\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\ESSD\AppData\Local\Programs\Python\Python38\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [WinError -2144272384] BitLocker 驱动器加密已锁定该驱动器。必须从控制面板解除此驱动器锁定。: 'D:\\'
2025-01-07 15:16:50,196 [INFO] 流程完成。
[DEBUG] Failed to add password protector.
[DEBUG] Return code: 2150694951
2025-01-07 15:20:42,186 [INFO] 程序已以管理员权限运行。
2025-01-07 15:20:42,187 [INFO] 程序已以管理员权限运行。
2025-01-07 15:20:42,187 [INFO] [INFO] Detected post-reboot. Running disable BitLocker logic...
BitLocker 驱动器加密: 配置工具版本 10.0.19041
版权所有 (C) 2013 Microsoft Corporation。保留所有权利。

请输入密码以解锁此卷: 
密码已成功解锁卷 D:。
2025-01-07 15:20:47,600 [INFO] FIO read write
2025-01-07 15:20:47,600 [INFO] Running command: fio.exe --name=seqwrite --rw=write --bs=128k --size=10G --directory=D\:\fio_test --filename=testfile --iodepth=1 --output=fio_log\seqwrite.log
fio: output file open error: No such file or directory
2025-01-07 15:20:47,665 [ERROR] Error during sequential write: Command 'fio.exe --name=seqwrite --rw=write --bs=128k --size=10G --directory=D\:\fio_test --filename=testfile --iodepth=1 --output=fio_log\seqwrite.log' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\code\bitlockerTest\test_case\t_Tcg_BitLocker_21_BaseRebootIoTest.py", line 186, in Run
    subprocess.run(fio_command, check=True, shell=True)
  File "C:\Users\ESSD\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'fio.exe --name=seqwrite --rw=write --bs=128k --size=10G --directory=D\:\fio_test --filename=testfile --iodepth=1 --output=fio_log\seqwrite.log' returned non-zero exit status 1.
2025-01-07 15:20:47,666 [INFO] Deleting test directory: D:\fio_test
2025-01-07 15:20:47,666 [INFO] Test directory deleted successfully.
2025-01-07 15:20:52,809 [INFO] [INFO] Task deleted.
2025-01-07 15:20:52,809 [INFO] [INFO] Workflow completed successfully.
2025-01-07 15:20:52,809 [INFO] 流程完成。
[DEBUG] Password protector added successfully.
2025-03-27 16:55:01,883 [INFO] 程序已以管理员权限运行。
2025-03-27 16:55:01,888 [INFO] [INFO] Detected post-reboot. Reboot finish...
2025-03-27 16:55:01,904 [INFO] [INFO] Task deleted.
2025-03-27 16:55:01,904 [INFO] [INFO] Workflow completed successfully.
2025-03-27 16:55:01,904 [INFO] 流程完成。
2025-03-27 17:02:46,918 [INFO] 程序已以管理员权限运行。
2025-03-27 17:02:46,918 [INFO] 程序已以管理员权限运行。
2025-03-27 17:02:46,922 [INFO] [INFO] Detected post-reboot. Running disable BitLocker logic...
BitLocker 驱动器加密: 配置工具版本 10.0.19041
版权所有 (C) 2013 Microsoft Corporation。保留所有权利。

请输入密码以解锁此卷: 
密码已成功解锁卷 D:。
2025-03-27 17:02:52,746 [INFO] FIO read write
2025-03-27 17:02:52,746 [INFO] Running command: fio.exe --name=seqwrite --rw=write --bs=128k --size=10G --directory=D\:\fio_test --filename=testfile --iodepth=1 --output=fio_log\seqwrite.log
fio: output file open error: No such file or directory
2025-03-27 17:02:52,765 [ERROR] Error during sequential write: Command 'fio.exe --name=seqwrite --rw=write --bs=128k --size=10G --directory=D\:\fio_test --filename=testfile --iodepth=1 --output=fio_log\seqwrite.log' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bitlockerTest\test_case\t_Tcg_BitLocker_21_BaseRebootIoTest.py", line 189, in Run
    subprocess.run(fio_command, check=True, shell=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'fio.exe --name=seqwrite --rw=write --bs=128k --size=10G --directory=D\:\fio_test --filename=testfile --iodepth=1 --output=fio_log\seqwrite.log' returned non-zero exit status 1.
2025-03-27 17:02:52,780 [INFO] Deleting test directory: D:\fio_test
2025-03-27 17:02:52,780 [INFO] Test directory deleted successfully.
2025-03-27 17:02:57,034 [INFO] [INFO] Task deleted.
2025-03-27 17:02:57,035 [INFO] [INFO] Workflow completed successfully.
2025-03-27 17:02:57,035 [INFO] 流程完成。
[DEBUG] Password protector added successfully.
